version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build-deploy:
    executor:
      name: node/default
      tag: '16.15'
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"

workflows:
  deploy:
    jobs:
      - build-deploy:
          context: Firebase
